bcgov/bc-emli-application-sys

app/frontend/components/domains/onboarding/eula/index.tsx, app/models/end_user_license_agreement.rb, app/models/user.rb, eulas/terms.html
=> feat: Add terms and conditions page [BCHEP-94]

app/frontend/components/domains/authentication/login-screen.tsx, app/frontend/components/domains/eligibility-check/index.tsx, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/misc/support-screen.tsx, app/frontend/components/shared/base/footer.tsx, app/frontend/components/shared/bcservicecard/contractor/index.tsx, app/frontend/components/shared/bcservicecard/info-block.tsx, app/frontend/styles/theme/components/button.ts, app/frontend/styles/theme/components/link.ts
=> Minor UI updates

app/frontend/components/shared/base/not-found-screen.tsx
=> refactor: Adjust the spacing on Page Not Found page

app/frontend/components/domains/eligibility-check/index.tsx, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/misc/support-screen.tsx, app/frontend/components/shared/base/footer.tsx, app/frontend/components/shared/bcservicecard/energy-coach/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/styles/theme/components/link.ts
=> refactor: minor ui changes requested for demo

app/blueprints/user_blueprint.rb, app/models/user.rb, app/models/user_address.rb, app/services/omniauth_user_resolver.rb, config/locales/en.yml, db/migrate/20250131011556_create_user_addresses.rb, db/migrate/20250131015246_remove_address_from_users.rb, db/schema.rb
=> feat(BCHEP-149): new user address table and model

app/frontend/i18n/i18n.ts
=> refactor: Applying UI changes as per ESP document requirements

docker-compose.yml
- run 'db:seed' on startup in Docker Compose
=> chore: run 'db:seed' on startup in Docker Compose

app/blueprints/program_blueprint.rb, app/blueprints/requirement_template_blueprint.rb, app/controllers/api/programs_controller.rb, app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/programs/index.tsx, app/frontend/components/domains/programs/new-program-screen.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/components/shared/program/contact-card.tsx, app/frontend/components/shared/program/manage-program-menu.tsx, app/frontend/components/shared/requirement-template/requirement-template-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-classification.ts, app/frontend/models/program-user-classification.ts, app/frontend/services/api/index.ts, app/frontend/services/rbac-rules.ts, app/frontend/stores/program-store.ts, app/frontend/stores/program-user-classification-store.ts, app/frontend/stores/root-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/live_requirement_template.rb, app/models/permit_classification.rb, app/models/program_type.rb, app/models/requirement_template.rb, app/models/user_type.rb, app/services/permit_classification_seeder.rb, config/locales/en.yml, db/migrate/20250402165828_add_user_and_program_type_id_to_requirement_templates.rb, db/schema.rb
Added UserType and ProgramType Classification
Changed business rule for edit program functionality
Added frontend models for the types
Changed Create Template form to use program type
Added routes for fetching program details and updating programs
=> feature: edit program, added new classifications

app/frontend/components/shared/base/not-found-screen.tsx
Silas Reviewed [BCHEP-151](https://apps.nrs.gov.bc.ca/int/jira/browse/BCHEP-151)
404 page:
Add a paragraph break after "The page you’re looking for might have been removed, moved, or is temporarily unavailable."
Add a paragraph break after "We suggest"
=> fix: Added a break between sentances as per BCHEP-151

app/frontend/components/domains/home/admin-manager-home-screen.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/shared/base/blue-title-bar.tsx, app/frontend/i18n/i18n.ts
BCHEP-204 - update icons and the hamburger menu on the admin manager screen
=> feature: update icons and the hamburger menu on the admin manager screen

app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/programs_controller.rb, app/frontend/components/domains/jurisdictions/submission-inbox/grid-header.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/base/inputs/async-dropdown.tsx, app/frontend/components/shared/grid/search-grid.tsx, app/frontend/components/shared/requirement-template/requirement-template-form.tsx, app/frontend/hooks/resources/use-program.ts, app/frontend/i18n/i18n.ts, app/frontend/models/permit-classification.ts, app/frontend/services/api/index.ts, app/frontend/stores/energy-savings-application-store.ts, app/frontend/stores/notification-store.ts, app/frontend/stores/permit-classification-store.ts, app/frontend/types/enums.ts, app/policies/permit_application_policy.rb, app/policies/program_policy.rb, app/policies/user_policy.rb, config/routes.rb
- Setup submission box for admin manager to work with programs instead of using Jurisdictions
- Resolved notification error
- modified dropdown to use 'useBoxWrapper' for different layouts
- modified policies to work with admin_manager
=> feature: submission inbox for admin manager

app/blueprints/program_classification_membership_blueprint.rb, app/blueprints/user_blueprint.rb, app/controllers/api/concerns/search/program_users.rb, app/controllers/api/program_classification_memberships_controller.rb, app/controllers/api/programs_controller.rb, app/controllers/concerns/base_controller_methods.rb, app/frontend/components/domains/programs/users/user-table-rows.tsx, app/frontend/models/program-classification.ts, app/frontend/models/program-membership.ts, app/frontend/models/user.ts, app/models/program.rb, app/models/program_classification_membership.rb, app/models/program_membership.rb, app/models/user.rb, db/migrate/20250424174917_add_deactivated_at_to_program_classification_memberships.rb, db/migrate/20250424235124_create_program_membership.rb, db/migrate/20250424235324_add_program_membership_to_program_classification_memberships.rb, db/migrate/20250424235524_backfill_program_memberships.rb, db/migrate/20250424235704_remove_user_and_program_from_program_classification_memberships.rb, db/schema.rb, spec/factories/program_classification_memebership.rb, spec/factories/program_memberships.rb, spec/models/program_membership_spec.rb, spec/requests/program_classification_memberships_spec.rb
this required refactor to allow for users to be deactivated & invited to/from single programs instead of entire application
=> refactor: program classification and membership

app/blueprints/site_configuration_blueprint.rb, app/controllers/api/site_configuration_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/sitewide-message-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/site-configuration-store.ts, app/frontend/types/api-request.ts, app/frontend/types/types.ts, db/migrate/20250430222646_add_sitewide_message_color_to_site_configurations.rb, db/schema.rb
feature: add sitewide message color column to site configurations. A system admin can change the color of the banner
=> feature: add sitewide message color column to site configurations. A system admin can change the color of the banner

app/blueprints/permit_application_blueprint.rb, app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/energy-savings-application/review-permit-application-screen.tsx, app/frontend/components/domains/energy-savings-application/successful-submission.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/application-rejection-reason.tsx, app/frontend/components/shared/modals/application-review-modal.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/energy-savings-application.ts, app/frontend/services/api/index.ts, app/frontend/styles/theme/foundations/colors.ts, app/frontend/types/enums.ts, app/models/permit_application.rb, app/policies/permit_application_policy.rb, config/routes.rb, db/schema.rb
- submission_type field added to submission inbox
- Mark for review and making application Ineligible functionality and UI added
-  Submission screen added
-  Made revision model generic
=> feature: review and reject flow included

app/frontend/components/domains/home/admin-manager-home-screen.tsx, app/models/requirement_template.rb
Couldn't reindex RequirementTemplate because nickname was missing &
=> feature: add the start application url for admin manager.  

app/controllers/api/notifications_controller.rb, app/frontend/components/domains/home/notifications/notifications-popover.tsx, app/frontend/services/api/index.ts, app/frontend/stores/notification-store.ts, app/policies/notification_policy.rb, app/services/notification_service.rb, config/routes.rb
feature: add delete notification functionality and clean up the "show more" notifications
=> feature: add delete notification functionality and clean up the "show more"

app/models/permit_application.rb, app/views/layouts/mailer.html.erb, app/views/permit_hub_mailer/notify_application_ineligible.erb, config/locales/en.yml
Updated the email template. This will break existing email notifications. Updated the notify_application_ineligible template. Added a reason to the in app notification
=> feature: update email template and add reason to notifications

app/blueprints/permit_application_blueprint.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/energy-savings-application/new-application.tsx, app/frontend/components/domains/programs/submission-inbox/program-submisson-inbox-screen.tsx, app/frontend/components/shared/base/inputs/async-dropdown.tsx, app/frontend/components/shared/energy-savings-applications/requirement-form.tsx, app/frontend/models/energy-savings-application.ts, app/frontend/services/api/index.ts, app/models/permit_application.rb, db/migrate/20250708145646_add_submitted_for_to_permit_applications.rb, db/schema.rb
- added submitted_for colum in permit_applications
- added functionality for showing submitter in submission box for application added on behalf of participants by admin/admin managers
- added name of application based on address if no address found
=> feature: added submitted_for column, new application changes

app/blueprints/permit_application_blueprint.rb, app/frontend/components/domains/energy-savings-application/assignment-management/designated-user-assignment-popover.tsx, app/frontend/components/domains/energy-savings-application/assignment-popover-content.tsx, app/frontend/components/shared/base/model-search-input.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/energy-savings-application.ts, app/frontend/stores/user-store.ts, app/services/application_assignments/assignment_management_service.rb
- Reduce debounce delay from 500ms to 300ms for faster response
- Skip expensive MST processing for assignment-only searches
- Add conditional skipMerge parameter to searchUsers method
- Fix blueprint naming: assigned_users -> assignedUsers for camelCase consistency
- Add backend idempotency check to prevent duplicate assignments
- Maintain backend as source of truth with API refresh after assignment
- Add visual feedback showing assigned users as disabled in dropdown
Performance: Reduces setTimeout violations from 84ms to ~25ms
Functionality: Assignment popup now shows proper enabled/disabled states
Architecture: Isolated optimization - no impact on user management pages
=>  fix: Optimize user search performance in assignment popup

app/blueprints/audit_log_blueprint.rb, app/controllers/api/audit_logs_controller.rb, app/controllers/api/omniauth_callbacks_controller.rb, app/controllers/api/sessions_controller.rb, app/frontend/components/domains/audit-log/index.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/shared/base/inputs/per-page-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/session-store.ts, app/frontend/stores/user-store.ts, app/helpers/audit_log_helper.rb, app/models/concerns/auditable.rb, app/models/user_license_agreement.rb, app/policies/audit_log_policy.rb, config/locales/en.yml, config/routes.rb
- Add AuditLog model with full CRUD tracking for all database changes
- Create audit log admin interface with filtering, pagination, and CSV export
- Implement login audit tracking in omniauth callbacks controller
- Add defensive programming patterns in frontend stores for null safety
- Refactor Auditable concern for DRY principles and better error handling
- Add comprehensive translations for audit log UI (frontend/backend)
- Include UserLicenseAgreement in audit tracking
- Simplify session validation logic and remove redundant authentication checks
- Add proper authorization policies restricting audit access to admin managers
- Implement responsive table design with horizontal scrolling for long data
- Configure CSV export limit via AUDIT_LOG_CSV_EXPORT_LIMIT env var (default: 50k …
=>   feature: implement comprehensive audit logging system with admin UI
